# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z4neL9q46JDL8KQx1si5VKXRsJ4kMoui
"""

import requests
import hashlib

session = requests.session()

response = session.get("http://167.99.198.129:30735/")
html = response.text

string_base64 = html[167:html.find("</h3>")]

hash = hashlib.md5(string_base64.encode()).hexdigest()

session.post("http://167.99.198.129:30735/", {"hash": hash}).text

